FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# radunauto

API per visualizzare, creare e gestire i raduni d'auto d'epoca.


## Registration [/api/users]

### Create a New User [POST]

Crea un nuovo utente nel sistema.

+ Request (application/json)

        {
            "username": "username",
            "password": "password",
            "email": "email"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/users

    + Body

            {
                "success": true,
                "message": "User saved successfully"
            }
            
            
## Login [/api/login]

### Login [POST]

Verifica username e password inseriti e fa accedere l'utente al sito.

+ Request (application/json)

        {
            "username": "username",
            "password": "password"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/login

    + Body

            {
                "success": true,
                "username": "username",
                "message": "Adesso che sei loggato, goditi il token!",
                "token": "token"
            }
            

## Logout [/api/logout]

### Logout [POST]

Revoca il token di accesso all'utente.

+ Request (application/json)

        {
            "cookie": "cookie"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/login

    + Body

            {
                "success": true,
                "message": "Logout avvenuto con successo"
            }
            

## Clubs [/api/clubs]

### List Clubs [GET]

Restituisce la lista dei club.

+ Response 200 (application/json)

        [
            {
                "name": "name",
                "owner": "owner"
            }
        ]

### Create a new club [POST]

Crea un nuovo club.

+ Request (application/json)

        {
            "name": "name",
            "owner": "owner"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/clubs

    + Body

            {
                "success": true,
                "message": "Club successfully created"
            }
                       

## Raduni [/api/raduni]

### Create a new event [POST]

Crea un nuovo raduno.

+ Request (application/json)

        {   
            "title": "title",
            "club": "club",
            "description": "description",
            "email": "email"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/raduni     

    + Body

            {
                "success": true,
                "message": "Event successfully created"
            }
            
### List raduni [GET]

Restituisce la lista dei raduni.

+ Response 201 (application/json)

    + Headers

            Location: /api/raduni     

    + Body

            {
                "title": "title",
                "description": "description",
                "club": "club",
                "email": "email"
            }